#! /bin/sh
# bootstrap        Bootstrap Script
# Copyright (C) 2000, 2002, 2003, 2005, ETG, Inc. All Rights Reserved.
#
# This file is proprietary and confidential and must not be distributed without the
# express permission of the copyright holder.
#
# See file COPYING for details.
#
# $Id: bootstrap,v 1.2 2003/06/10 03:53:34 jshiffer Exp $
#
#
# History:  -jshiffer 12/19/00 3:53pm: Created.


(test -d aux_files) || {
 mkdir -p aux_files;
}

# libtoolize generates support for libtool
# autoheader generates config.h.in by scanning acconfig.h
# aclocal generates aclocal.m4 by scanning configure.in
# automake generates Makefile.in by scanning Makefile.am
# autoconf generates configure by scanning configure.in
progvar ()
{
    #
    # see if the first choice exists
    #
    local VV=$1; shift
    local i
    local R

    eval R=\\\$"$VV"
    eval R=$R

    if [ x"${R}" \!= x"" ]; then
        # the environment alread sets it
        return;
    fi

    while [ $# -gt 0 -a x"$V" = x"" ]; do
        type $1 > /dev/null 2>&1
        if [[ $? = 0 ]]; then
            V=$1
        fi
        shift;
    done

    eval $VV=$V
    unset V
}

error () {
    echo "$1: failed with $?"
    exit 1
}

# find the apps and set if necessary
progvar LIBTOOLIZE glibtoolize libtoolize
progvar ACLOCAL aclocal
progvar AUTOHEADER autoheader
progvar AUTOCONF autoconf
progvar AUTOMAKE automake
progvar AUTORECONF autoreconf



#if [ -f configure -a -n ${AUTORECONF} ]; then
#    set -x
#    ${AUTORECONF} || error "${AUTORECONF}"
#else
set -x
${LIBTOOLIZE} --automake --copy --force || error "${LIBTOOLIZE}"
${ACLOCAL} -I aux_files || error "${ACLOCAL}"
${AUTOHEADER} || error "${AUTOHEADER}"
${AUTOCONF} || error "${AUTOCONF}"
${AUTOMAKE} --add-missing --copy --foreign || error "${AUTOMAKE}"
#fi

# set +x
# if [ x${AUTOMAKE} == x"unsermake" ]; then
#     set -x
#     unsermake -c || error "unsermake"
# fi

