#!/usr/bin/perl -w

my %CDATA = ();
my $USAGE = <<EOF;
usage:
$0 [opts] [component] [[sub][...]]

opts:
-p generate a component with a public interface (for optimizations)
-c generate the main component
-s generate 1 or more subs
-m generate a Makefile.am
-o overwrite files

subs will be generated thus:
  a sub of unix would generate a file <component>/<component>_unix.[ch]
  and functions <component>_unix...
EOF

use strict;
use Getopt::Std;

if(@ARGV < 1){
    print $USAGE;
    exit;
}

my %options = ();

getopts("hpcsmo", \%options);

if(defined $options{h}) {
    print $USAGE;
    exit 0;
}

$CDATA{PUBLIC} = $options{p} if defined $options{p};
$CDATA{GENCOMP} = $options{c} if defined $options{c};
$CDATA{GENSUBS} = $options{s} if defined $options{s};
$CDATA{GENMAKE} = $options{m} if defined $options{m};
$CDATA{OVERWRITE} = $options{o} if defined $options{o};


$CDATA{LOCALDIR} = $ENV{PWD};
$CDATA{LOCALDIR} =~ s/.*\/(\w+)/$1/;

my $name = shift;
if($name){
    my @sub_modules = ();
    if(@ARGV){
	@sub_modules = @ARGV;
    }
    $CDATA{name} = $name;
    $CDATA{NAME} = $name;
    $CDATA{NAME} =~ tr/a-z/A-Z/;
    $CDATA{SUBS} = \@sub_modules;
    mk_component(%CDATA);
}else{
    print $USAGE;
exit 1;
}
exit;

sub mk_component {
    my (%DATA) = @_;
    my $name = $DATA{name};

    if(!$DATA{OVERWRITE}){
      # test for the files and directories that we need
      if(-e $name){ print "A file or directory named \"$name\" already exists! exiting\n"; exit; }
      if(-e "$name.c"){ print "A file named \"$name.c\" already exists! exiting\n"; exit; }
      if(-e "$name.h"){ print "A file named \"$name.h\" already exists! exiting\n"; exit; }
    }

    # create the directory
    if(! -d $name){mkdir $name, 0777;}

    my $PRIVATE = gen_private_interface($name);
    my $PUBLIC = gen_public_interface($name);
    my $WARNING = gen_opt_warning($name);

    if($DATA{PUBLIC}){
	$DATA{PUBLIC_INTERFACE} = "$WARNING $PUBLIC $PRIVATE";
	$DATA{PRIVATE_INTERFACE} = "";
    }else{
	$DATA{PUBLIC_INTERFACE} = "$PUBLIC";
	$DATA{PRIVATE_INTERFACE} = "$PRIVATE";
    }

    # make the main files
    if($DATA{GENCOMP}){
      print_public_c("$name.c", %DATA);
      print_public_h("$name.h", %DATA);
      print_private_c("$name/$name" . "_private.c", %DATA);
      print_private_h("$name/$name" . "_private.h", %DATA);
      print_interface_h("$name/$name" . "_interface.h", %DATA);
    }

    if($DATA{GENSUBS}){
      my $sub = "";
      foreach $sub (@{$DATA{SUBS}}){
	print_sub_h($sub, %DATA);
	print_sub_c($sub, %DATA);
      }
    }

    if($DATA{GENMAKE}){
      print_makefile_am(%DATA);
    }
}

sub print_interface_h {
  my ($file, %DATA) = @_;
  open(FILE, "> $file") || die "Cannot open file $file: $!";
  print FILE <<EOF;
#ifndef _$DATA{NAME}_INTERFACE_H_
#define _$DATA{NAME}_INTERFACE_H_

#include <$DATA{LOCALDIR}/$DATA{name}.h>

EOF
  my $sub = "";
  foreach $sub (@{$DATA{SUBS}}){
    print FILE "#include <$DATA{LOCALDIR}/$DATA{name}/$DATA{name}_$sub.h>", "\n";
  }
  print FILE <<EOF;
#endif  /* _$DATA{NAME}_INTERFACE_H_ */
EOF
}

sub print_sub_h {
    my($sub, %DATA) = @_;
    my $SUB = $sub;
    $SUB =~ tr/a-z/A-Z/;
    open(FILE, "> $DATA{name}/$DATA{name}_$sub.h") || die "Cannot open file $DATA{name}/$DATA{name}_$sub.c: $!";
  print FILE <<EOF;
#ifndef _$DATA{NAME}_${SUB}_H_
#define _$DATA{NAME}_${SUB}_H_

#include <$DATA{LOCALDIR}/$DATA{name}.h>

#ifdef __cplusplus
#define extern "C" {
#pragma }
#endif /* __cplusplus */

extern $DATA{name}_ty *
$DATA{name}_$sub(void);

#ifdef __cplusplus
}
#endif
#endif  /* _$DATA{NAME}_${SUB}_H_ */
EOF
    close(FILE);
}
sub print_sub_c {
    my($sub, %DATA) = @_;
    my $sub_ty = $sub . "_ty";
    open(FILE, "> $DATA{name}/$DATA{name}_$sub.c") || die "Cannot open file $DATA{name}/$DATA{name}_$sub.c: $!";
    print FILE <<EOF;

#include "$DATA{name}_private.h"

/* local declarations */
static void destructor($DATA{name}_ty *$DATA{name});

/* component data */
/* Uncomment to create a private data section
 * also check $DATA{name}_vtbl_ty
 *
 * typedef struct $DATA{name}_$sub $DATA{name}_$sub;
 * struct $DATA{name}_$sub {
 *   $DATA{name}_ty      inherited;
 */
     /* private data */
 /* };
  */
static $DATA{name}_vtbl_ty vtbl = {
/* for private data uncomment the following line and
 * remove the $DATA{name}_ty
 * sizeof($DATA{name}_$sub_ty), 
 */
  sizeof($DATA{name}_ty),
  destructor,
};

$DATA{name}_ty *
$DATA{name}_$sub(void)
{
    $DATA{name}_ty	* result;
    /* $DATA{name}_$sub_ty * $sub; */

    result = $DATA{name}_new(&vtbl);
    /* $sub = ($DATA{name}_$sub_ty *)result; */
    /* do local work here */

    return result;
}

/* local definitions */
static void 
destructor($DATA{name}_ty *$DATA{name})
{
    return;
}

EOF
    close(FILE);
}

sub print_makefile_am {
    my (%DATA) = @_;
    my $sub = "";
    open(FILE, "> $DATA{name}/Makefile.am") || die "Cannot open file $DATA{name}/Makefile.am: $!";
    print FILE <<EOF;
noinst_LTLIBRARIES = lib$DATA{name}.la

lib$DATA{name}_la_SOURCES = \\
		$DATA{name}_private.c \\
EOF
    my $num = scalar(@{$DATA{SUBS}});
    foreach $sub (@{$DATA{SUBS}}){
	if($num == 1){
	    print FILE "		$DATA{name}_$sub.c", "\n";
	}else{
	    print FILE "		$DATA{name}_$sub.c \\", "\n";
	}
	$num--;
    }
    print FILE <<EOF;

DEFS := \@DEFS\@ -I/usr/include -I. -I\$(srcdir) -I../..

pkgincludedir = \${includedir}/$DATA{name}
pkginclude_HEADERS = \\
		$DATA{name}_private.h \\
EOF
    $num = scalar(@{$DATA{SUBS}});
    foreach $sub (@{$DATA{SUBS}}){
	if($num == 1){
	    print FILE "		$DATA{name}_$sub.h", "\n";
	}else{
	    print FILE "		$DATA{name}_$sub.h \\", "\n";
	}
	$num--;
    }
    print FILE <<EOF;

include \$(top_srcdir)/Makefile.extra
EOF
    close(FILE);
}
sub print_public_c {
    my ($file, %DATA) = @_;
    open(CFILE, "> $file") || die "Cannot open file $file: $!";
    print CFILE <<EOF;

#include "$name.h"

EOF
    close(CFILE);
}

sub print_public_h {
  my ($file, %DATA) = @_;
  open(FILE, "> $file") || die "Cannot open file $file: $!";

  print FILE <<EOF;
#ifndef _$DATA{NAME}_H_
#define _$DATA{NAME}_H_

#ifdef __cplusplus
#define extern "C" {
#pragma }
#endif /* __cplusplus */

$DATA{PUBLIC_INTERFACE}

#ifdef __cplusplus
}
#endif

#include <$DATA{LOCALDIR}/$DATA{name}/$DATA{name}_interface.h>

#endif  /* _$DATA{NAME}_H_ */
EOF
close(FILE);
}

sub print_private_c {
    my ($file, %DATA) = @_;
    open(FILE, "> $file") || die "Cannot open file $file: $!";
    print FILE <<EOF;
#include <stdlib.h>
#include "$DATA{name}_private.h"

${name}_ty*
${name}_new (${name}_vtbl_ty *vptr)
{
  ${name}_ty *result;
  result = calloc(1, vptr->size);
  result->vtbl = vptr;
  return(result);
}
EOF
    close(FILE);
}

sub print_private_h {
  my ($file, %DATA) = @_;
  my $name = $DATA{name};

  open(FILE, "> $file") || die "Cannot open file $file: $!";
  print FILE <<EOF;
/* Private interface to $name
 * You should NOT access this directly
 * unless you are extending the component
 */
#ifndef _$DATA{NAME}_PRIVATE_H_
#define _$DATA{NAME}_PRIVATE_H_

#include <stdlib.h>
#include <$DATA{LOCALDIR}/${name}.h>

#ifdef __cplusplus
#define extern "C" {
#pragma }
#endif /* __cplusplus */

$DATA{PRIVATE_INTERFACE}

${name}_ty *${name}_new (${name}_vtbl_ty *);
#ifdef __cplusplus
}
#endif
#endif  /* _$DATA{NAME}_PRIVATE_H_ */
EOF
    close(FILE);
}

sub gen_private_interface {
  $name = shift;
  my $INTERFACE = <<EOF;
struct ${name}_ty {
  struct ${name}_vtbl_ty *vtbl;
  /* rest of opts */
};
  
typedef struct ${name}_vtbl_ty ${name}_vtbl_ty;
struct ${name}_vtbl_ty {
  size_t size;
  /* virtual function pointers */
  void (* destructor)(${name}_ty *);
};
EOF
  return ($INTERFACE);
}

sub gen_public_interface {
  my $name = shift;
  my $INTERFACE = "typedef struct ${name}_ty ${name}_ty;";
  return $INTERFACE;
}

sub gen_opt_warning {
  my $name = shift;
  my $WARNING = <<EOF;
/* This is here for optimization purposes
 * you should not access this directly unless
 * you are extending the component
 */
EOF
return $WARNING;
}
